// Generated by CoffeeScript 1.9.0
(function() {
  angular.module("forumApp", ['ngRoute', 'firebase']).constant("FBUrl", "FIREBASE-URL").config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'templates/home.html',
      controller: 'HomeCtrl'
    }).when('/create', {
      templateUrl: 'templates/create.html',
      controller: 'CreateCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
