// Generated by CoffeeScript 1.9.0
(function() {
  angular.module("forumApp").controller("HomeCtrl", [
    "$scope", "FirebaseFactory", function($scope, FirebaseFactory) {
      var topics;
      topics = FirebaseFactory.getFbRef("topics").$asArray();
      return $scope.topics = topics;
    }
  ]).controller("CreateCtrl", [
    "$scope", "FirebaseFactory", function($scope, FirebaseFactory) {
      return $scope.postTopic = function() {
        var topics;
        $scope.post.likes = 0;
        $scope.post.dislikes = 0;
        return topics = FirebaseFactory.insertToFb($scope.post, "topics").then(function(data) {
          alert("The topic has been saved");
          return $scope.post = '';
        });
      };
    }
  ]);

}).call(this);
